# Setup
title:    Prog 2
tagline:  Introduci贸n a la Programaci贸n II
baseurl:  /prog2
zip:	    https://github.com/FacultadDeIngenieria/prog2/zipball/gh-pages

# About/contact
author:
name:       Introduci贸n a la Programaci贸n II
